### ISSUE TITLE
TBC vanilla dungeon levels

### ISSUE THREAD

**Issue by jarosr93** [fs86/LFG_MatchMaker_TBC#5]
Hello, thank you so much for this addon. Is really helpfull :-). I noticed one thing. Vanilla dungeons levels look like from Classic Era, not from Classic TBC. Could you please update min and max levels for vanilla dungeons? I (38 level) was at RFK where the addon suggest 30 - 40 level (wowhead too) but all mobs was gray. So, i checked Atlas and they suggest level range 24 - 40. Which look correct (min level, dont know why max is 40 level). Do you plan some update about ranges? Thanks you. Roman.

**Comment by fs86** [comment]
Oh, thanks for letting me know. I didn't know that. Will be changed in the next version :-)

**Comment by fs86** [comment]
Done with version 1.0.4
